' UML Diagram for Semester, Course, Tag, and GUI

@startuml
class Semester {
    - _year : int
    - _season : str
    - _courses : list[tuple[str, int]
    + year() : int
    + year(val : int)
    + season() : str
    + season(val : str)
    + courses() : list[tuple[str, int]
    + courses(arr : list[tuple[str, int])
    __str__() : str
}

class Course {
    - _name : str
    - _number : int
    - _dept : Tag
    + name() : str
    + name(val : str)
    + number() : int
    + number(val : int)
    + dept() : Tag
    + dept(val : Tag)
    __str__() : str
}

class Tag {
    - _name : str
    - _description : str
    + name() : str
    + name(val : str)
    + description() : str
    + description(val : str)
    __str__() : str
}

class GUI {
    - _file : str
    - _tag : str

}

class GuiEventHandler {
    - pickfile() : str
    - pickpath(Tag : str) : str
    - savefileas(file : str, dir : str)
    + getTag(file : str) : str
    + setTag(Tag : str)
}

GUI --> GuiEventHandler : uses
GuiEventHandler --> Semester : uses
Semester --> Course : uses
Semester --> Tag : uses
Course --> Tag : uses

@enduml
