@startuml
actor User
participant GUI
participant EventHandler
participant Semester
participant Course
participant Tag

User -> GUI : click "Pick Dir"
GUI -> EventHandler : populatelist()
EventHandler --> GUI : list of files in dir

User -> GUI : click files in list
User -> GUI : select year
User -> GUI : select class
User -> GUI : SaveFiles()

GUI -> EventHandler : SaveFiles()
EventHandler -> Course : dept()
Course --> EventHandler : Tag
EventHandler -> Tag : name()
Tag --> EventHandler : tag name

EventHandler --> GUI : file saved

GUI --> User : show success message
@enduml
